#pragma once

#ifndef ENABLE_UI_LAB
#define ENABLE_UI_LAB 0
#endif

#ifndef ENABLE_UI_LAB_ADVANCED_TUNING
#define ENABLE_UI_LAB_ADVANCED_TUNING 0
#endif

#ifndef ENABLE_SERIAL_DEBUG_COMMANDS
#define ENABLE_SERIAL_DEBUG_COMMANDS 0
#endif

#ifndef ENABLE_SERIAL_VIRTUAL_BUTTONS
#define ENABLE_SERIAL_VIRTUAL_BUTTONS 1
#endif
