#pragma once

#ifndef ENABLE_UI_LAB
#define ENABLE_UI_LAB 0
#endif

#ifndef ENABLE_UI_LAB_ADVANCED_TUNING
#define ENABLE_UI_LAB_ADVANCED_TUNING 0
#endif

#ifndef ENABLE_SERIAL_DEBUG_COMMANDS
#define ENABLE_SERIAL_DEBUG_COMMANDS 0
#endif

#ifndef ENABLE_SERIAL_IO
#define ENABLE_SERIAL_IO 0
#endif

#ifndef ENABLE_SERIAL_VIRTUAL_BUTTONS
#define ENABLE_SERIAL_VIRTUAL_BUTTONS 0
#endif

#ifndef ENABLE_LONG_RUN_STATS
#define ENABLE_LONG_RUN_STATS 0
#endif

#ifndef ENABLE_INTERNAL_TEMPERATURE_MONITOR
#define ENABLE_INTERNAL_TEMPERATURE_MONITOR 0
#endif

#ifndef ENABLE_APP_WATCHDOG
#define ENABLE_APP_WATCHDOG 1
#endif

#ifndef APP_WATCHDOG_TIMEOUT_SEC
#define APP_WATCHDOG_TIMEOUT_SEC 15
#endif

#ifndef ENABLE_SINGLE_BOOT_BUTTON
#define ENABLE_SINGLE_BOOT_BUTTON 1
#endif

#ifndef USER_BOOT_BUTTON_PIN
#define USER_BOOT_BUTTON_PIN 0
#endif

#ifndef USER_BOOT_BUTTON_ACTIVE_LOW
#define USER_BOOT_BUTTON_ACTIVE_LOW 1
#endif
